### ISSUE TITLE
problems with SSR rendering / nuxt

### ISSUE THREAD

**Issue by sebolek** [InnerSearch/vue-innersearch#14]
I can't seem to get vue-innersearch to work with nuxt.js or any other ssr framework such as express, do you have any pointers/suggestions on how I would accomplish that? (it works fine on client only side, but with ssr i get window is undefined)

**Comment by Sackeys** [comment]
Thank you for your report. Unfortunately, we have mainly worked on a client-side application and we don't have the required skills about the server-side render in Vue.js. At this time, we can't give you an effective solution.
However, we would be delighted to have some help in order to solve this issue. Please do not hesitate to contribute to our project.
