### ISSUE TITLE
[Question] Is there any CDN link?

### ISSUE THREAD

**Issue by fsaiyedOB** [InnerSearch/vue-innersearch#9]
Is there any CDN JS link to directly use this in HTML project?

**Comment by TrimA74** [comment]
Not yet, we are currently working on it

It will be available soon on the next release

**Comment by TrimA74** [comment]
There you go.

https://unpkg.com/vue-innersearch@0.0.9/vue-innersearch.min.js

An example is avaible here :

http://jsbin.com/jazezahevi/edit?html,output



:warning: **CORS need to be enable on your browser in order to make the example work**

[Allow-Control-Allow-Origin: *](https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi)
